on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

name: Publish NPM package
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: install
        run: npm install --legacy-peer-deps
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
      - name: build
        run: npm run build
      #- name: print diff if failed
      #  if: ${{ failure() }}
      #  run: cp dist/temp/decentraland-ecs-utils.api.md report/decentraland-ecs-utils.api.md && git diff
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          #cwd: ./dist
          access: public # 'public' to deploy @scoped/packages
          ## Sign the deployment
          provenance: false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
