on:
  push:
    branches:
      - master
  pull_request:
  release:
    types:
      - created

name: Publish NPM package
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: install
        run: npm ci --legacy-peer-deps
      - name: build
        run: npm run build
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          access: public # 'public' to deploy @scoped/packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
